name: GitHub Actions
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Debug env
      run: env
    - name: List current dir
      run: ls; pwd; echo *
    - name: Python run
      run: python debug.py
